
[terminal.shell]
program = "/usr/bin/bash"
args = ["-l"]

# Environment

[general]
# Alacritty - TOML configuration file format.


# import = ["~/.config/alacritty/themes/themes/dracula_plus.toml"]

[window]
startup_mode = "Windowed"
title = "Alacritty"
dynamic_title = true 
decorations_theme_variant = "None"
decorations = "Full"
opacity = 0.9
blur = true 


# SCROLLING

[scrolling]
history = 10000
multiplier = 3


# FONT

[font]
normal = { family = "MartianMono Nerd Font Mono", style = "Regular" }
size = 12
builtin_box_drawing = true 

# COLORS

# Default colors

# BELL


[bell]
animation = "Linear"
duration = 0



# SELECTION
# This section documents the [selection] table of the configuration file.
# semantic_escape_chars = "<string>"
# This string contains all characters that are used as separators for "semantic words" in Alacritty.

# Default: ",│`|:\"' ()[]{}<>\t"

# save_to_clipboard = true | false
# When set to true, selected text will be copied to the primary clipboard.
# Default: false

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = false


# CURSOR

[cursor]
style = { shape = "Block", blinking = "Off" }
unfocused_hollow = true
thickness = 0.15


# MOUSE

[mouse]
hide_when_typing = false



[terminal]

