# main packages

packages=(
    lolcat
    innoextract
    sl
    cmatrix
    htop
    lame
    curl
    git
    flatpak
    fortune-mod
    fortunes
    cowsay
    cowsay-off
    vlc
    qcomicbook
    strawberry
)
