#!/bin/bash

sudo apt update && sudo apt install --ignore-missing -y \
  gnome-core \
  yaru-theme-{gnome-shell,gtk,icon,sound,unity} \
  fonts-ubuntu fonts-ubuntu-{title,console} ttf-mscorefonts-installer \
  rpi-chromium-mods chromium chromium-common chromium-driver chromium-l10n gnome-browser-connector \
  rhythmbox rhythmbox-plugins rhythmbox-plugin-alternative-toolbar \
  gstreamer1.0-plugins-{base,good,bad,ugly} gstreamer1.0-{libav,tools,alsa,pulseaudio,x,gl,vaapi,pipewire} libwidevinecdm0 \
  libreoffice-{writer,calc,impress,gtk3,gnome} \
  gnome-text-editor simple-scan hplip file-roller \
  network-manager-openvpn-gnome \
  gnome-tweaks gnome-calendar gnome-weather \
  plymouth plymouth-themes gnome-shell-extension-dashtodock gnome-shell-extension-desktop-icons-ng gnome-shell-extensions \
  dbus-x11 || true && \
sudo mkdir -p /etc/skel/.config/autostart /etc/dconf/db/local.d && mkdir -p ~/.config/autostart && \
echo -e 'user-db:user\nsystem-db:local' | sudo tee /etc/dconf/profile/user >/dev/null && \
sudo sh -c 'mkdir -p /etc/skel/.config/autostart && printf %b "[Desktop Entry]\nType=Application\nName=Chromium Autostart\nExec=chromium --headless --remote-debugging-port=9222 about:blank\nIcon=chromium\nX-GNOME-Autostart-enabled=true\n" > /etc/skel/.config/autostart/Chromium_Autostart.desktop && chmod 644 /etc/skel/.config/autostart/Chromium_Autostart.desktop' && cp /etc/skel/.config/autostart/Chromium_Autostart.desktop ~/.config/autostart/ && \
sudo chmod 644 /etc/skel/.config/autostart/Chromium_Autostart.desktop && \
cp /etc/skel/.config/autostart/Chromium_Autostart.desktop ~/.config/autostart/ && \
sudo sh -c 'mkdir -p /etc/skel/.config/autostart && printf %b "#!/bin/bash\ngsettings set org.gtk.gtk4.Settings.FileChooser sort-directories-first true\ngsettings set org.gnome.calculator refresh-interval 0\ngsettings set org.gnome.mutter dynamic-workspaces false\ngsettings set org.gnome.nautilus.list-view use-tree-view true\ngsettings set org.gnome.desktop.wm.preferences num-workspaces 2\ngsettings set org.gnome.desktop.background picture-uri \"file:///usr/share/backgrounds/gnome/blobs-l.svg\"\ngsettings set org.gnome.desktop.background picture-uri-dark \"file:///usr/share/backgrounds/gnome/blobs-d.svg\"\ngsettings set org.gnome.desktop.background primary-color \"#241f31\"\ngsettings set org.gnome.desktop.interface accent-color \"orange\"\ngsettings set org.gnome.desktop.interface gtk-theme \"Yaru\"\ngsettings set org.gnome.desktop.interface icon-theme \"Yaru\"\ngsettings set org.gnome.desktop.interface cursor-theme \"Yaru\"\ngsettings set org.gnome.shell.extensions.user-theme name \"Yaru\"\ngsettings set org.gnome.shell enabled-extensions \"['dash-to-dock@micxgx.gmail.com','ding@rastersoft.com','user-theme@gnome-shell-extensions.gcampax.github.com','topiconsfix@aleskva@devnullmail.com','app-hider@lynith.dev','gnome-fuzzy-app-search@gnome-shell-extensions.Czarlie.gitlab.com','add-to-desktop@tommimon.github.com']\"\ngsettings set org.gnome.shell favorite-apps \"['chromium.desktop','org.gnome.Nautilus.desktop','libreoffice-writer.desktop','org.gnome.Software.desktop','yelp.desktop','org.gnome.Settings.desktop']\"\nrm -f \"\$HOME/.config/autostart/gsettings.desktop\"\nrm -- \"\$0\"\n" > /etc/skel/.config/autostart/gsettings.sh && chmod 755 /etc/skel/.config/autostart/gsettings.sh' && install -D -m 755 /etc/skel/.config/autostart/gsettings.sh ~/.config/autostart/gsettings.sh && \
sudo chmod +x /etc/skel/.config/autostart/gsettings.sh && \
cp /etc/skel/.config/autostart/gsettings.sh ~/.config/autostart/ && \
sudo sh -c 'mkdir -p /etc/skel/.config/autostart && printf %b "[Desktop Entry]\nType=Application\nName=GNOME fallback settings\nExec=/bin/bash -c \"sleep 10; \$HOME/.config/autostart/gsettings.sh\"\nIcon=org.gnome.Nautilus\nX-GNOME-Autostart-enabled=true\n" > /etc/skel/.config/autostart/gsettings.desktop && chmod 644 /etc/skel/.config/autostart/gsettings.desktop' && cp /etc/skel/.config/autostart/gsettings.desktop ~/.config/autostart/ && \
sudo chmod 644 /etc/skel/.config/autostart/gsettings.desktop && \
cp /etc/skel/.config/autostart/gsettings.desktop ~/.config/autostart/ && \
echo -e "[org/gnome/mutter]\nexperimental-features=['scale-monitor-framebuffer']" | sudo tee /etc/dconf/db/local.d/01-gnome-mutter >/dev/null && \
echo -e "[org/gnome/shell]\nenabled-extensions=['dash-to-dock@micxgx.gmail.com','ding@rastersoft.com','user-theme@gnome-shell-extensions.gcampax.github.com']\n\n[org/gnome/shell/extensions/dash-to-dock]\ndock-position='LEFT'\nextend-height=true\ndash-max-icon-size=64\nshow-trash=false\nintellihide-mode='ALL_WINDOWS'\nrunning-indicator-style='DOTS'\n\n[org/gnome/shell/extensions/ding]\nicon-size='small'\n\n[org/gnome/shell/extensions/user-theme]\nname='Yaru'\n\n[org/gnome/shell]\nfavorite-apps=['chromium.desktop','org.gnome.Nautilus.desktop','libreoffice-writer.desktop','org.gnome.Software.desktop','yelp.desktop','org.gnome.Settings.desktop']" | sudo tee /etc/dconf/db/local.d/02-gnome-shell >/dev/null && \
echo -e "[org/gnome/desktop/interface]\ngtk-theme='Yaru'\nicon-theme='Yaru'\ncursor-theme='Yaru'\nfont-name='Ubuntu 11'\ndocument-font-name='Ubuntu 11'\nmonospace-font-name='Ubuntu Mono 13'\n\n[org/gnome/desktop/wm/preferences]\nbutton-layout=':minimize,maximize,close'\n\n[org/gnome/desktop/background]\npicture-uri='file:///usr/share/backgrounds/gnome/blobs-l.svg'\n\n[org/gnome/desktop/interface]\nenable-hot-corners=false" | sudo tee /etc/dconf/db/local.d/03-gnome-desktop >/dev/null && \
echo -e "[org/gnome/nautilus/preferences]\ndefault-folder-viewer='list-view'\nsort-directories-first=true" | sudo tee /etc/dconf/db/local.d/04-gnome-nautilus >/dev/null && \
PKGS=""; readarray -t CODES < <( { [ -f /etc/locale.gen ] && awk 'NF && $1 !~ /^#/ {print $1}' /etc/locale.gen; grep -E '^(LANG|LANGUAGE)=' /etc/default/locale 2>/dev/null | sed 's/.*=//' | tr ':' '\n'; [ -f "/var/lib/AccountsService/users/$(id -un)" ] && awk -F= '/^Language=/{print $2}' "/var/lib/AccountsService/users/$(id -un)"; [ -n "${LANG:-}" ] && echo "$LANG"; [ -n "${LANGUAGE:-}" ] && printf '%s\n' $LANGUAGE; } | sed -E 's/[[:space:]]+//g' | sed -E 's/[.@].*$//' | awk 'NF{gsub("_","-"); print tolower($0)}' | awk '!seen[$0]++' ); echo "Detected languages: ${CODES[*]}"; WANT=(hunspell hyphen libreoffice-l10n libreoffice-help); for code in "${CODES[@]}"; do echo "➡ Language: $code"; L="${code%%-*}"; for typ in "${WANT[@]}"; do if [ "$typ" = "libreoffice-l10n" ] && [ "$code" = "en-us" ]; then echo "  ↷ skip $typ for en-us"; continue; fi; found=""; for cand in "$typ-$code" "$typ-$L"; do if apt-cache show "$cand" >/dev/null 2>&1 && ! apt-cache policy "$cand" | grep -q 'Candidate: (none)'; then found="$cand"; break; fi; done; if [ -z "$found" ]; then while read -r alt; do [[ -z "$alt" ]] && continue; [[ "$alt" =~ ^$typ- ]] || continue; if apt-cache policy "$alt" | grep -qv 'Candidate: (none)'; then found="$alt"; break; fi; done < <(apt-cache search "^$typ-$L-" | awk '{print $1}'); fi; if [ -n "$found" ]; then case " $PKGS " in *" $found "* ) : ;; * ) PKGS+=" $found"; echo "  ✔ $typ → $found";; esac; else echo "  ⚠ No package found for $typ ($code)"; fi; done; done; if [ -n "$PKGS" ]; then echo "Installing:$PKGS"; sudo apt-get update -y >/dev/null 2>&1 || true; sudo apt-get install --ignore-missing -y $PKGS || true; echo "Done."; else echo "Nothing to do."; fi; dpkg -l locales-all 2>/dev/null | grep -q '^ii' && echo "ℹ 'locales-all' is installed; we deliberately avoid 'locale -a'." && \
wget -O /tmp/topiconsfix.zip https://extensions.gnome.org/extension-data/topiconsfixaleskvadevnullmail.com.v23.shell-extension.zip && sudo rm -rf /usr/share/gnome-shell/extensions/topiconsfix@aleskva@devnullmail.com && sudo unzip -o /tmp/topiconsfix.zip -d /usr/share/gnome-shell/extensions/topiconsfix@aleskva@devnullmail.com && sudo chmod -R a+rX /usr/share/gnome-shell/extensions/topiconsfix@aleskva@devnullmail.com && \
wget -O /tmp/gnome-fuzzy-app-search.zip https://extensions.gnome.org/extension-data/gnome-fuzzy-app-searchgnome-shell-extensions.Czarlie.gitlab.com.v26.shell-extension.zip && sudo rm -rf /usr/share/gnome-shell/extensions/gnome-fuzzy-app-search@gnome-shell-extensions.Czarlie.gitlab.com && sudo unzip -o /tmp/gnome-fuzzy-app-search.zip -d /usr/share/gnome-shell/extensions/gnome-fuzzy-app-search@gnome-shell-extensions.Czarlie.gitlab.com && sudo chmod -R a+rX /usr/share/gnome-shell/extensions/gnome-fuzzy-app-search@gnome-shell-extensions.Czarlie.gitlab.com && \
wget -O /tmp/add-to-desktop.zip https://extensions.gnome.org/extension-data/add-to-desktoptommimon.github.com.v15.shell-extension.zip && sudo rm -rf /usr/share/gnome-shell/extensions/add-to-desktop@tommimon.github.com && sudo unzip -o /tmp/add-to-desktop.zip -d /usr/share/gnome-shell/extensions/add-to-desktop@tommimon.github.com && sudo chmod -R a+rX /usr/share/gnome-shell/extensions/add-to-desktop@tommimon.github.com && \
wget -O /tmp/libreoffice_yaru-themes_2025-09-23.zip https://wobbo.org/download/libreoffice_yaru-themes_2025-09-23.zip && sudo unzip -o /tmp/libreoffice_yaru-themes_2025-09-23.zip -d /usr/lib/libreoffice/share/config/ 'images_yaru*.zip' && cd /usr/lib/libreoffice/share/config/ && for f in images_yaru*.zip; do [[ "$f" == *_dark.zip ]] && continue; sudo mv -f "$f" "${f%.zip}_dark.zip"; done && sudo unzip -o /tmp/libreoffice_yaru-themes_2025-09-23.zip -d /usr/lib/libreoffice/share/config/ && sudo chmod -R a+rX /usr/lib/libreoffice/share/config/images_yaru* && ls -1 images_yaru*_dark.zip | wc -l && rm -f /tmp/libreoffice_yaru-themes_2025-09-23.zip && cd ~ && \
tmpdir=$(mktemp -d); cd "$tmpdir"; wget https://wobbo.org/download/yaru-theme-gnome-shell_25.04.1-0ubuntu1_all.deb https://wobbo.org/download/yaru-theme-gtk_25.04.1-0ubuntu1_all.deb https://wobbo.org/download/yaru-theme-icon_25.04.1-0ubuntu1_all.deb https://wobbo.org/download/yaru-theme-sound_25.04.1-0ubuntu1_all.deb https://wobbo.org/download/geary_44.1-1wobbo1_arm64_20251202.deb; sudo apt install -y ./yaru-theme-*.deb ./geary_44.1-1wobbo1_arm64_20251202.deb; sudo apt-mark hold yaru-theme-gnome-shell yaru-theme-gtk yaru-theme-icon yaru-theme-sound geary; apt-cache policy geary | grep Installed; cd ~; rm -rf "$tmpdir" && \
sudo wget -O /usr/local/bin/gnome-auto-yaru.sh https://wobbo.org/download/gnome-auto-yaru_2025-10-07.sh && sudo chmod 755 /usr/local/bin/gnome-auto-yaru.sh && sudo wget -O /etc/systemd/user/gnome-auto-yaru.service https://wobbo.org/download/gnome-auto-yaru_2025-10-07.service && sudo chmod 644 /etc/systemd/user/gnome-auto-yaru.service && sudo systemctl daemon-reload && systemctl --user daemon-reload && sudo systemctl enable --global gnome-auto-yaru.service && systemctl --user restart gnome-auto-yaru.service && \
sudo sh -c 'printf %b "#!/bin/bash\nsed -i '\''s/^StartupNotify=true/StartupNotify=false/'\'' /usr/share/applications/chromium.desktop\n" > /usr/local/bin/fix_chromium_notify.sh' && sudo chmod 755 /usr/local/bin/fix_chromium_notify.sh && sudo sh -c 'printf %b "[Unit]\nDescription=Fix Chromium .desktop StartupNotify\nAfter=network.target\n[Service]\nType=oneshot\nExecStart=/usr/local/bin/fix_chromium_notify.sh\nRemainAfterExit=true\n[Install]\nWantedBy=multi-user.target\n" > /etc/systemd/system/fix-chromium-notify.service' && sudo chmod 644 /etc/systemd/system/fix-chromium-notify.service && sudo systemctl daemon-reload && sudo systemctl enable --now fix-chromium-notify.service && \
sudo dconf update && \
sudo plymouth-set-default-theme bgrt -R && \
sudo cp /boot/firmware/cmdline.txt /boot/firmware/cmdline.txt.backup && sudo sed -i '1 s/^/splash quiet plymouth.ignore-serial-consoles /' /boot/firmware/cmdline.txt && \
sudo awk 'BEGIN{sec="";aw=0;pw=0} function ov(l){return l ~ /^\s*#?\s*dtoverlay=vc4-.*v3d/} { if($0 ~ /^\s*\[/){ if(sec=="[all]"&&!aw){print "dtoverlay=vc4-kms-v3d\n";aw=1} if(sec=="[pi5]"&&!pw){print "dtoverlay=vc4-kms-v3d-pi5\n";pw=1} sec=$0; if(NR>1 && prev!~"^$") print ""; print; prev=$0; next } if(ov($0)) next; print; prev=$0 } END{ if(sec=="[all]"&&!aw){print "dtoverlay=vc4-kms-v3d\n";aw=1} if(sec=="[pi5]"&&!pw){print "dtoverlay=vc4-kms-v3d-pi5\n";pw=1} if(!aw){print "[all]\ndtoverlay=vc4-kms-v3d\n"} if(!pw){print "[pi5]\ndtoverlay=vc4-kms-v3d-pi5\n"} }' /boot/firmware/config.txt | sudo tee /boot/firmware/config.txt.tmp >/dev/null && sudo cp -a /boot/firmware/config.txt /boot/firmware/config.txt.bak && sudo mv /boot/firmware/config.txt.tmp /boot/firmware/config.txt && \
sudo apt remove -y firefox firefox-esr im-config totem mpv htop && \
sudo apt autoremove -y && \
sudo sed -i '/^logo=/ s/^/#/' /etc/gdm3/greeter.dconf-defaults && \
sudo systemctl set-default graphical.target && \
sudo reboot 